### ISSUE TITLE
the confirm email link it is not working

### ISSUE THREAD

**Issue by AdelEddarai** [cocola-dev/cocola#107]
the confirm email link it is not working, it direct me to undefined link;

   http://undefined/new-verification?token=******

**Comment by ruru-m07** [comment]
## sorry about that i mostly focus on some section like 

- /
- /settings
- /login
- /chat/copilot
- /new
- /:user
- /:user/:repo
- /:user/:repo/issue 
- /:user/:repo/issue/new
- `and more`

but i need to focus on signup page that page contain many bugs and issue i want something deferent for that page that's why i not working on it now.

but today i starting working on it.

for now i give u permission to login to your account i edit email verification via DB changes.

thanks for visiting and make this issue, happy coding @AdelEddarai
